### ISSUE TITLE
Home page not responding

### ISSUE THREAD

**Issue by nckx** [dparks1134/ExpressBetaDiversity#11]
Hi!  This might sort itself out as soon as I press ‘Submit’, but http://kiwi.cs.dal.ca/Software/ExpressBetaDiversity isn't responding here.

Is there a new URL [we could use](https://guix.gnu.org/packages/express-beta-diversity-1.0.8/)?  Thanks!

**Comment by dparks1134** [comment]
I'm afraid the server running the kiwi server was compromised and the ExpressBetaDiversity information hosted there is unlikely to be recovered. However, I think all relevant information is in the README.md file on the GitHub page. Is there something specific you were after?

**Comment by nckx** [comment]
> Is there something specific you were after?

Not really, just ‘the most complete home page’ for our users.

I guess that is the README now, so I'll use https://github.com/dparks1134/ExpressBetaDiversity and close this issue.  Thanks for the fast response!
