### ISSUE TITLE
Interpretation of the result

### ISSUE THREAD

**Issue by julipeale2001** [dparks1134/ExpressBetaDiversity#15]
Thanks for developing the tool.
I would like to know if the dissimilarity output is in form of percentage as in the output below:
5
D28
D42 0.853644
D0	0.891928 0.89667
D8	0.86205	0.876258 0.887934
D84 0.856588 0.863442 0.898884 0.867226

Can I say that the dissimilarity between D28 and D42 is 85.4%?

**Comment by donovan-h-parks** [comment]
Hi. No, it isn't a percent. The exact interpretation depends on the beta diversity measure you selected. Often these have a value between 0 (identical) and 1 (no overlap), though not always.

**Comment by julipeale2001** [comment]
[like]  Nweze Julius reacted to your message:
________________________________
