### ISSUE TITLE
scripts included in distrubution?

### ISSUE THREAD

**Issue by wwood** [dparks1134/ExpressBetaDiversity#7]
Hey,

I'm trying to package ebd in guix and just wondering whether these scripts should be distributed?
```
convertToFullMatrix.py
pcoaPlot.py
```
Neither of these are chmod +x and there's no mention of them in the readme I saw, is all.
ta

**Comment by dparks1134** [comment]
I'd say no since they are undocumented 'helper' scripts that may be deprecated at this point.
